/**
 * أسماء الله الحُسنى — the 99 Beautiful Names of Allah (the well-known list
 * transmitted via al-Walīd b. Muslim in Tirmidhī). Each entry carries the
 * Arabic name, a Latin transliteration, an English meaning and a brief Arabic
 * meaning. Bundled offline.
 *
 * The Prophet ﷺ said: "Allah has ninety-nine names; whoever enumerates them
 * enters Paradise." (Bukhārī · Muslim)
 */

export type DivineName = {
  /** 1-based position in the traditional list. */
  n: number;
  arabic: string;
  translit: string;
  en: string;
  arMeaning: string;
};

export const DIVINE_NAMES: DivineName[] = [
  { n: 1, arabic: 'الرَّحْمَٰن', translit: 'Ar-Raḥmān', en: 'The Most Compassionate', arMeaning: 'الواسع الرحمة بجميع خلقه' },
  { n: 2, arabic: 'الرَّحِيم', translit: 'Ar-Raḥīm', en: 'The Most Merciful', arMeaning: 'الرحيم بالمؤمنين' },
  { n: 3, arabic: 'الْمَلِك', translit: 'Al-Malik', en: 'The Sovereign King', arMeaning: 'المالك لكل شيء' },
  { n: 4, arabic: 'الْقُدُّوس', translit: 'Al-Quddūs', en: 'The Most Holy', arMeaning: 'المنزَّه عن كل نقص' },
  { n: 5, arabic: 'السَّلَام', translit: 'As-Salām', en: 'The Source of Peace', arMeaning: 'السالم من كل عيب' },
  { n: 6, arabic: 'الْمُؤْمِن', translit: 'Al-Muʾmin', en: 'The Granter of Security', arMeaning: 'المصدِّق لرسله، المؤمِّن عباده' },
  { n: 7, arabic: 'الْمُهَيْمِن', translit: 'Al-Muhaymin', en: 'The Guardian', arMeaning: 'الرقيب الحافظ على خلقه' },
  { n: 8, arabic: 'الْعَزِيز', translit: 'Al-ʿAzīz', en: 'The Almighty', arMeaning: 'الغالب الذي لا يُغلَب' },
  { n: 9, arabic: 'الْجَبَّار', translit: 'Al-Jabbār', en: 'The Compeller', arMeaning: 'القاهر لخلقه، جابر الكسر' },
  { n: 10, arabic: 'الْمُتَكَبِّر', translit: 'Al-Mutakabbir', en: 'The Supreme in Greatness', arMeaning: 'المتعالي عن صفات الخلق' },
  { n: 11, arabic: 'الْخَالِق', translit: 'Al-Khāliq', en: 'The Creator', arMeaning: 'الموجِد للأشياء من العدم' },
  { n: 12, arabic: 'الْبَارِئ', translit: 'Al-Bāriʾ', en: 'The Originator', arMeaning: 'المبدِع للخلق بلا مثال' },
  { n: 13, arabic: 'الْمُصَوِّر', translit: 'Al-Muṣawwir', en: 'The Fashioner', arMeaning: 'مصوِّر الخلق كيف شاء' },
  { n: 14, arabic: 'الْغَفَّار', translit: 'Al-Ghaffār', en: 'The Ever-Forgiving', arMeaning: 'كثير المغفرة للذنوب' },
  { n: 15, arabic: 'الْقَهَّار', translit: 'Al-Qahhār', en: 'The All-Subduer', arMeaning: 'القاهر لكل شيء' },
  { n: 16, arabic: 'الْوَهَّاب', translit: 'Al-Wahhāb', en: 'The Bestower', arMeaning: 'كثير العطاء بلا عوض' },
  { n: 17, arabic: 'الرَّزَّاق', translit: 'Ar-Razzāq', en: 'The Provider', arMeaning: 'الرازق لجميع خلقه' },
  { n: 18, arabic: 'الْفَتَّاح', translit: 'Al-Fattāḥ', en: 'The Opener, The Judge', arMeaning: 'الحاكم بين عباده، فاتح الخير' },
  { n: 19, arabic: 'الْعَلِيم', translit: 'Al-ʿAlīm', en: 'The All-Knowing', arMeaning: 'العالم بكل شيء' },
  { n: 20, arabic: 'الْقَابِض', translit: 'Al-Qābiḍ', en: 'The Withholder', arMeaning: 'القابض للأرزاق بحكمته' },
  { n: 21, arabic: 'الْبَاسِط', translit: 'Al-Bāsiṭ', en: 'The Extender', arMeaning: 'الباسط للرزق لمن يشاء' },
  { n: 22, arabic: 'الْخَافِض', translit: 'Al-Khāfiḍ', en: 'The Abaser', arMeaning: 'خافض المتكبرين' },
  { n: 23, arabic: 'الرَّافِع', translit: 'Ar-Rāfiʿ', en: 'The Exalter', arMeaning: 'رافع المؤمنين بالطاعة' },
  { n: 24, arabic: 'الْمُعِزّ', translit: 'Al-Muʿizz', en: 'The Honourer', arMeaning: 'معطي العز لمن يشاء' },
  { n: 25, arabic: 'الْمُذِلّ', translit: 'Al-Mudhill', en: 'The Humiliator', arMeaning: 'مذلّ من يشاء بعدله' },
  { n: 26, arabic: 'السَّمِيع', translit: 'As-Samīʿ', en: 'The All-Hearing', arMeaning: 'السامع لكل صوت' },
  { n: 27, arabic: 'الْبَصِير', translit: 'Al-Baṣīr', en: 'The All-Seeing', arMeaning: 'المبصِر لكل شيء' },
  { n: 28, arabic: 'الْحَكَم', translit: 'Al-Ḥakam', en: 'The Judge', arMeaning: 'الحاكم العدل بين خلقه' },
  { n: 29, arabic: 'الْعَدْل', translit: 'Al-ʿAdl', en: 'The Utterly Just', arMeaning: 'العادل في حكمه' },
  { n: 30, arabic: 'اللَّطِيف', translit: 'Al-Laṭīf', en: 'The Subtle, The Gentle', arMeaning: 'اللطيف بعباده، العالم بالدقائق' },
  { n: 31, arabic: 'الْخَبِير', translit: 'Al-Khabīr', en: 'The All-Aware', arMeaning: 'العالم ببواطن الأمور' },
  { n: 32, arabic: 'الْحَلِيم', translit: 'Al-Ḥalīm', en: 'The Forbearing', arMeaning: 'الذي لا يعجل بالعقوبة' },
  { n: 33, arabic: 'الْعَظِيم', translit: 'Al-ʿAẓīm', en: 'The Magnificent', arMeaning: 'العظيم في ذاته وصفاته' },
  { n: 34, arabic: 'الْغَفُور', translit: 'Al-Ghafūr', en: 'The All-Forgiving', arMeaning: 'الستار للذنوب الغافر لها' },
  { n: 35, arabic: 'الشَّكُور', translit: 'Ash-Shakūr', en: 'The Most Appreciative', arMeaning: 'المجازي على القليل بالكثير' },
  { n: 36, arabic: 'الْعَلِيّ', translit: 'Al-ʿAliyy', en: 'The Most High', arMeaning: 'العالي فوق خلقه' },
  { n: 37, arabic: 'الْكَبِير', translit: 'Al-Kabīr', en: 'The Most Great', arMeaning: 'الكبير الذي كل شيء دونه' },
  { n: 38, arabic: 'الْحَفِيظ', translit: 'Al-Ḥafīẓ', en: 'The Preserver', arMeaning: 'الحافظ لخلقه وأعمالهم' },
  { n: 39, arabic: 'الْمُقِيت', translit: 'Al-Muqīt', en: 'The Sustainer', arMeaning: 'المقتدر، المُقيت للأبدان والأرواح' },
  { n: 40, arabic: 'الْحَسِيب', translit: 'Al-Ḥasīb', en: 'The Reckoner', arMeaning: 'الكافي، المحاسب لعباده' },
  { n: 41, arabic: 'الْجَلِيل', translit: 'Al-Jalīl', en: 'The Majestic', arMeaning: 'الموصوف بصفات الجلال' },
  { n: 42, arabic: 'الْكَرِيم', translit: 'Al-Karīm', en: 'The Most Generous', arMeaning: 'كثير الخير، الجواد المعطي' },
  { n: 43, arabic: 'الرَّقِيب', translit: 'Ar-Raqīb', en: 'The Watchful', arMeaning: 'المراقب لكل شيء' },
  { n: 44, arabic: 'الْمُجِيب', translit: 'Al-Mujīb', en: 'The Responsive', arMeaning: 'المجيب لدعاء عباده' },
  { n: 45, arabic: 'الْوَاسِع', translit: 'Al-Wāsiʿ', en: 'The All-Encompassing', arMeaning: 'الواسع الفضل والرحمة' },
  { n: 46, arabic: 'الْحَكِيم', translit: 'Al-Ḥakīm', en: 'The All-Wise', arMeaning: 'المحكم لخلقه، ذو الحكمة' },
  { n: 47, arabic: 'الْوَدُود', translit: 'Al-Wadūd', en: 'The Most Loving', arMeaning: 'المحبّ لأوليائه' },
  { n: 48, arabic: 'الْمَجِيد', translit: 'Al-Majīd', en: 'The Most Glorious', arMeaning: 'العظيم الكريم في صفاته' },
  { n: 49, arabic: 'الْبَاعِث', translit: 'Al-Bāʿith', en: 'The Resurrector', arMeaning: 'باعث الخلق يوم القيامة' },
  { n: 50, arabic: 'الشَّهِيد', translit: 'Ash-Shahīd', en: 'The Witness', arMeaning: 'الشاهد على كل شيء' },
  { n: 51, arabic: 'الْحَقّ', translit: 'Al-Ḥaqq', en: 'The Absolute Truth', arMeaning: 'الثابت الذي لا يتغير' },
  { n: 52, arabic: 'الْوَكِيل', translit: 'Al-Wakīl', en: 'The Trustee', arMeaning: 'المتكفل بأمور خلقه' },
  { n: 53, arabic: 'الْقَوِيّ', translit: 'Al-Qawiyy', en: 'The All-Strong', arMeaning: 'الكامل القدرة' },
  { n: 54, arabic: 'الْمَتِين', translit: 'Al-Matīn', en: 'The Firm', arMeaning: 'الشديد القوة الذي لا يلحقه تعب' },
  { n: 55, arabic: 'الْوَلِيّ', translit: 'Al-Waliyy', en: 'The Protecting Friend', arMeaning: 'الناصر، وليّ المؤمنين' },
  { n: 56, arabic: 'الْحَمِيد', translit: 'Al-Ḥamīd', en: 'The Praiseworthy', arMeaning: 'المحمود على كل حال' },
  { n: 57, arabic: 'الْمُحْصِي', translit: 'Al-Muḥṣī', en: 'The Counter', arMeaning: 'المحيط بكل شيء عددًا' },
  { n: 58, arabic: 'الْمُبْدِئ', translit: 'Al-Mubdiʾ', en: 'The Originator', arMeaning: 'المبتدئ خلق الأشياء' },
  { n: 59, arabic: 'الْمُعِيد', translit: 'Al-Muʿīd', en: 'The Restorer', arMeaning: 'المعيد للخلق بعد الفناء' },
  { n: 60, arabic: 'الْمُحْيِي', translit: 'Al-Muḥyī', en: 'The Giver of Life', arMeaning: 'المحيي للأموات والقلوب' },
  { n: 61, arabic: 'الْمُمِيت', translit: 'Al-Mumīt', en: 'The Bringer of Death', arMeaning: 'المميت للأحياء بأجلهم' },
  { n: 62, arabic: 'الْحَيّ', translit: 'Al-Ḥayy', en: 'The Ever-Living', arMeaning: 'الحي الذي لا يموت' },
  { n: 63, arabic: 'الْقَيُّوم', translit: 'Al-Qayyūm', en: 'The Self-Subsisting', arMeaning: 'القائم بنفسه المقيم لغيره' },
  { n: 64, arabic: 'الْوَاجِد', translit: 'Al-Wājid', en: 'The Perceiver', arMeaning: 'الغني الذي لا يفتقر' },
  { n: 65, arabic: 'الْمَاجِد', translit: 'Al-Mājid', en: 'The Noble', arMeaning: 'الكريم العظيم المجد' },
  { n: 66, arabic: 'الْوَاحِد', translit: 'Al-Wāḥid', en: 'The One', arMeaning: 'المنفرد بالوحدانية' },
  { n: 67, arabic: 'الْأَحَد', translit: 'Al-Aḥad', en: 'The Indivisible One', arMeaning: 'الفرد الذي لا نظير له' },
  { n: 68, arabic: 'الصَّمَد', translit: 'Aṣ-Ṣamad', en: 'The Eternal Refuge', arMeaning: 'المقصود في الحوائج، الغني عن كل أحد' },
  { n: 69, arabic: 'الْقَادِر', translit: 'Al-Qādir', en: 'The All-Powerful', arMeaning: 'القادر على كل شيء' },
  { n: 70, arabic: 'الْمُقْتَدِر', translit: 'Al-Muqtadir', en: 'The Omnipotent', arMeaning: 'كامل القدرة لا يمتنع عليه شيء' },
  { n: 71, arabic: 'الْمُقَدِّم', translit: 'Al-Muqaddim', en: 'The Expediter', arMeaning: 'المقدِّم للأشياء في مواضعها' },
  { n: 72, arabic: 'الْمُؤَخِّر', translit: 'Al-Muʾakhkhir', en: 'The Delayer', arMeaning: 'المؤخِّر للأشياء بحكمته' },
  { n: 73, arabic: 'الْأَوَّل', translit: 'Al-Awwal', en: 'The First', arMeaning: 'الذي ليس قبله شيء' },
  { n: 74, arabic: 'الْآخِر', translit: 'Al-Ākhir', en: 'The Last', arMeaning: 'الذي ليس بعده شيء' },
  { n: 75, arabic: 'الظَّاهِر', translit: 'Aẓ-Ẓāhir', en: 'The Manifest', arMeaning: 'الظاهر فوق كل شيء' },
  { n: 76, arabic: 'الْبَاطِن', translit: 'Al-Bāṭin', en: 'The Hidden', arMeaning: 'العالم بالخفايا، الأقرب من كل شيء' },
  { n: 77, arabic: 'الْوَالِي', translit: 'Al-Wālī', en: 'The Patron', arMeaning: 'المالك للأشياء المتصرف فيها' },
  { n: 78, arabic: 'الْمُتَعَالِي', translit: 'Al-Mutaʿālī', en: 'The Most Exalted', arMeaning: 'المتنزه عن صفات المخلوقين' },
  { n: 79, arabic: 'الْبَرّ', translit: 'Al-Barr', en: 'The Source of Goodness', arMeaning: 'المحسن إلى عباده' },
  { n: 80, arabic: 'التَّوَّاب', translit: 'At-Tawwāb', en: 'The Acceptor of Repentance', arMeaning: 'القابل لتوبة عباده' },
  { n: 81, arabic: 'الْمُنْتَقِم', translit: 'Al-Muntaqim', en: 'The Avenger', arMeaning: 'المنتقم من العصاة بعدله' },
  { n: 82, arabic: 'الْعَفُوّ', translit: 'Al-ʿAfuww', en: 'The Pardoner', arMeaning: 'الماحي للسيئات' },
  { n: 83, arabic: 'الرَّؤُوف', translit: 'Ar-Raʾūf', en: 'The Most Kind', arMeaning: 'الرحيم الرفيق بعباده' },
  { n: 84, arabic: 'مَالِكُ الْمُلْك', translit: 'Mālik al-Mulk', en: 'Owner of All Sovereignty', arMeaning: 'المالك للملك يؤتيه من يشاء' },
  { n: 85, arabic: 'ذُو الْجَلَالِ وَالْإِكْرَام', translit: 'Dhul-Jalāli wal-Ikrām', en: 'Lord of Majesty & Honour', arMeaning: 'صاحب العظمة والفضل' },
  { n: 86, arabic: 'الْمُقْسِط', translit: 'Al-Muqsiṭ', en: 'The Equitable', arMeaning: 'العادل في قضائه' },
  { n: 87, arabic: 'الْجَامِع', translit: 'Al-Jāmiʿ', en: 'The Gatherer', arMeaning: 'الجامع للخلق ليوم القيامة' },
  { n: 88, arabic: 'الْغَنِيّ', translit: 'Al-Ghaniyy', en: 'The Self-Sufficient', arMeaning: 'الغني عن كل ما سواه' },
  { n: 89, arabic: 'الْمُغْنِي', translit: 'Al-Mughnī', en: 'The Enricher', arMeaning: 'المغني لعباده من فضله' },
  { n: 90, arabic: 'الْمَانِع', translit: 'Al-Māniʿ', en: 'The Withholder', arMeaning: 'المانع لأهل الفساد بحكمته' },
  { n: 91, arabic: 'الضَّارّ', translit: 'Aḍ-Ḍārr', en: 'The Distresser', arMeaning: 'الذي بيده الضر بقضائه' },
  { n: 92, arabic: 'النَّافِع', translit: 'An-Nāfiʿ', en: 'The Benefactor', arMeaning: 'الذي بيده النفع كله' },
  { n: 93, arabic: 'النُّور', translit: 'An-Nūr', en: 'The Light', arMeaning: 'نور السماوات والأرض، الهادي' },
  { n: 94, arabic: 'الْهَادِي', translit: 'Al-Hādī', en: 'The Guide', arMeaning: 'الهادي عباده إلى الحق' },
  { n: 95, arabic: 'الْبَدِيع', translit: 'Al-Badīʿ', en: 'The Incomparable Originator', arMeaning: 'مبدع الخلق بلا مثال سابق' },
  { n: 96, arabic: 'الْبَاقِي', translit: 'Al-Bāqī', en: 'The Everlasting', arMeaning: 'الدائم الذي لا يفنى' },
  { n: 97, arabic: 'الْوَارِث', translit: 'Al-Wārith', en: 'The Ultimate Inheritor', arMeaning: 'الباقي بعد فناء الخلق' },
  { n: 98, arabic: 'الرَّشِيد', translit: 'Ar-Rashīd', en: 'The Guide to the Right Path', arMeaning: 'المرشد إلى مصالح العباد' },
  { n: 99, arabic: 'الصَّبُور', translit: 'Aṣ-Ṣabūr', en: 'The Most Patient', arMeaning: 'الذي لا يعجل بعقوبة العصاة' },
];
