import { HADITHS } from './data';
import { Hadith } from './types';

/**
 * The full bundled library = the curated entries (rich: narrator, isnād,
 * explanation) plus the large `corpus.json` set (thousands of narrations across
 * all six collections, generated by scripts/fetch-hadiths.js).
 *
 * corpus.json is required lazily so its ~5 MB parse only happens when the Hadith
 * tab first opens — it never slows app startup. For *complete* (30k+) coverage,
 * move to a bundled SQLite DB or online search (see README).
 */
let cache: Hadith[] | null = null;

export async function loadLibrary(): Promise<Hadith[]> {
  if (cache) return cache;
  // Yield a frame so the require()/parse doesn't block the first interaction.
  await new Promise((r) => setTimeout(r, 0));
  let corpus: Hadith[] = [];
  try {
    corpus = require('./corpus.json') as Hadith[];
  } catch {
    corpus = [];
  }
  const curatedIds = new Set(HADITHS.map((h) => h.id));
  // Curated first (so their rich data wins), then the rest of the corpus.
  cache = [...HADITHS, ...corpus.filter((h) => !curatedIds.has(h.id))];
  return cache;
}

/** Synchronous lookup once the library is loaded; falls back to curated. */
export function findInLibrary(id: string): Hadith | undefined {
  return (cache ?? HADITHS).find((h) => h.id === id);
}

export function libraryCount(): number {
  return cache?.length ?? HADITHS.length;
}
