import React from 'react';
import { Image, ImageStyle, StyleProp } from 'react-native';

import { useTheme } from '@/theme';

// A true transparent silhouette (generated by scripts/make-mark.js), so
// `tintColor` recolors only the mark — works on light and dark backgrounds.
// (The original logo_trans.png has an opaque white background and can't tint.)
const MARK = require('../../assets/brand/mark.png');

type LogoProps = {
  size?: number;
  /** Any color string; defaults to the theme primary. Pass null to keep the
   *  original teal artwork untinted. */
  color?: string | null;
  style?: StyleProp<ImageStyle>;
};

export function Logo({ size = 40, color, style }: LogoProps) {
  const theme = useTheme();
  const tintColor = color === null ? undefined : color ?? theme.colors.primary;
  return (
    <Image
      source={MARK}
      accessibilityLabel="Athar logo"
      resizeMode="contain"
      style={[{ width: size, height: size, tintColor }, style]}
    />
  );
}
